name: GitHub ENV
on: push

jobs:
  github-env-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_ENV

      - run: echo "test=test1test2test3" >> $GITHUB_ENV

      - run: echo ${{ env.test }}
