name: inline-env
on: push

env:
  test1: aaa
jobs:
  inline-env:
    runs-on: ubuntu-latest
    steps:
      - env: 
          test2: bbb
        run: |
          echo "${{ env.test1 }}"
          echo "${{ env.test2 }}"
          echo "${{ env.test3 }}"
