name: kensyou1
on: push

env:
  hensuu: koreha hensuudesu

jobs:
  hensuu-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test-jobが実行される"
      - run: echo "${{ env.hensuu }}"
      - run: echo "$hensuu"
  working-directory-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cicd-section
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls
  name-job:
    runs-on: ubuntu-latest
    steps:
      - name: ネームジョブのステップ1
        run: pwd
  secret-mask-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "secretsは*でマスクされるか？ ${{ secrets.abcdef }}"
  multi-step-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.sha }}
          echo ${{ github.sha }}
  id-job:
    runs-on: ubuntu-latest
    steps:
      - name: $GITHUB_OUTPUTを出力する
        run: echo "$GITHUB_OUTPUT"
      - name: 本来はoutputに対して描き込む(とりあえずpwd)
        id: kakikomi
        run: echo "message=id:kakikomiのstepから書き込まれた文字列です。" >> $GITHUB_OUTPUT
      - name: idを書き込んだstepのoutputsを取得する
        run: echo "${{ steps.kakikomi.outputs }}"
      - name: idを書き込んだstepから値を取得する
        run: echo ${{ steps.kakikomi.outputs.message }}