name: kensyou1
on: push

env:
  hensuu: koreha hensuudesu

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test-jobが実行される"
      - run: echo "${{ env.hensuu }}"
      - run: echo "$hensuu"