name: kensyou1
on: push

env:
  hensuu: koreha hensuudesu

jobs:
  hensuu-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test-jobが実行される"
      - run: echo "${{ env.hensuu }}"
      - run: echo "$hensuu"
  working-directory-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cicd-section
    steps:
      - run: pwd
      - run: ls